//USER
export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const USER_POSTS_STATE_CHANGE = "USER_POSTS_STATE_CHANGE";
export const ADD_USER_DATA_TO_POST = "ADD_USER_DATA_TO_POST";
export const USER_FOLLOWING_STATE_CHANGE = "USER_FOLLOWING_STATE_CHANGE";
export const USER_LIKES_STATE_CHANGE = "USER_LIKES_STATE_CHANGE";

//USERS
export const USERS_DATA_STATE_CHANGE = "USERS_DATA_STATE_CHANGE";
export const USERS_POSTS_STATE_CHANGE = "USERS_POSTS_STATE_CHANGE";
export const RELOAD_USERS_POSTS = "RELOAD_USERS_POSTS";
export const USERS_LIKES_STATE_CHANGE = "USERS_LIKES_STATE_CHANGE";
export const REMOVE_POSTS_UNFOLLOWED_USER = "REMOVE_POSTS_UNFOLLOWED_USER";
export const LIKE_POST_USER = "LIKE_POST_USER";
export const DISLIKE_POST_USER = "DISLIKE_POST_USER";

//COMMON
export const CLEAR_DATA = "CLEAR_DATA";

//UI
export const SET_LOADING = "SET_LOADING";
